apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
bases:
  - https://github.com/argoproj/argo-cd/tree/master/manifests/cluster-install?ref=v2.14.10 
resources:
  - resources/namespace.yaml 