apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  admin.enabled: "true"
  timeout.reconciliation: 40s
  resource.customizations: |
    ConfigMap:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        hs.message = "ConfigMap managed"
        return hs
