apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- argocd-rbac-cm.yaml
patches:
- path: patches/argocd-cm.yaml
  target:
    kind: ConfigMap
    name: argocd-cm
