apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  application.resourceTrackingMethod: annotation
  admin.enabled: "true"
  resource.customizations: |
    ConfigMap:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        hs.message = "ConfigMap managed"
        return hs
  repositories: |
    - url: https://github.com/deegbo/apps-appset.git
      type: git
    - url: https://github.com/deegbo/argocd-appSet.git
      type: git
    - url: https://github.com/deegbo/infra-home-argocd.git
      type: git